# Generated by Django 5.2.14 on 2026-08-03 13:17

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Boardroom'), (2, 'Bastion'), (3, 'Kraaijenbergse Plassen')], default=0, verbose_name='Location')),
                ('is_reservable', models.BooleanField(default=True, help_text='When an item is unavailable for reservation, due to maintenance for example, set this to false.', verbose_name='Reservable')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Material type')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Boat'), (2, 'Room'), (3, 'Material')], default=0, verbose_name='Reservable category')),
                ('description', models.TextField(verbose_name='Type description')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservableBoat',
            fields=[
                ('reservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservable')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacity')),
                ('has_engine', models.BooleanField(default=False, verbose_name='Boat has an engine')),
                ('provider', models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Loefbijter'), (2, 'Ceulemans')], default=0, verbose_name='Boat provider')),
                ('requires_skippership', models.CharField(blank=True, choices=[('KB1', 'KB1'), ('KB2', 'KB2'), ('KB3', 'KB3'), ('Pico', 'Pico')], help_text='The skippership required to use this boat.', max_length=10, verbose_name='Required skippership')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('reservations.reservable',),
        ),
        migrations.CreateModel(
            name='ReservableMaterial',
            fields=[
                ('reservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservable')),
                ('size', models.CharField(max_length=10, verbose_name='Size')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('reservations.reservable',),
        ),
        migrations.CreateModel(
            name='ReservableRoom',
            fields=[
                ('reservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservable')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacity')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('reservations.reservable',),
        ),
        migrations.AddField(
            model_name='reservable',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservabletype'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('request_status', models.PositiveSmallIntegerField(choices=[(0, 'In behandeling'), (1, 'Goedgekeurd'), (2, 'Geweigerd')], default=0, verbose_name='Request status')),
                ('start', models.DateTimeField(verbose_name='Start time')),
                ('end', models.DateTimeField(verbose_name='End time')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'In behandeling'), ('accepted', 'Goedgekeurd'), ('denied', 'Geweigerd')], default='pending', max_length=20, verbose_name='Status')),
                ('denial_reason', models.TextField(blank=True, verbose_name='Denial reason')),
                ('authorized_userskippership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_userskippership_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Authorized skipper')),
                ('reservable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoatLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('wind_force', models.PositiveSmallIntegerField(verbose_name='Wind force (Bft)')),
                ('motor_hours', models.PositiveIntegerField(verbose_name='Motor hours')),
                ('refueled', models.BooleanField(default=False, verbose_name='Did you refuel the boat?')),
                ('has_new_damage', models.BooleanField(default=False, verbose_name='Did you discover new damage?')),
                ('new_damage_description', models.TextField(blank=True, verbose_name='New damage description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reservations/boat-logbooks/', verbose_name='Photo of the boat')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boat_logbook', to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoatDamageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.TextField(verbose_name='Damage description')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_records', to='reservations.reservableboat', verbose_name='Boat')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='end_gt_start', violation_error_message='End time cannot be before the start time.'),
        ),
    ]
