# Generated by Django 6.0.7 on 2026-08-02 13:52

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_add_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="request_status",
            field=models.PositiveSmallIntegerField(choices=[(0, "In behandeling"), (1, "Goedgekeurd"), (2, "Geweigerd")], default=0, verbose_name="Request status"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(choices=[("pending", "In behandeling"), ("accepted", "Goedgekeurd"), ("denied", "Geweigerd")], default="pending", max_length=20, verbose_name="Status"),
        ),
        migrations.CreateModel(
            name="BoatDamageRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified")),
                ("description", models.TextField(verbose_name="Damage description")),
                ("boat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="damage_records", to="reservations.boat", verbose_name="Boat")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BoatLogbook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified")),
                ("wind_force", models.PositiveSmallIntegerField(verbose_name="Wind force (Bft)")),
                ("motor_hours", models.PositiveIntegerField(verbose_name="Motor hours")),
                ("refueled", models.BooleanField(default=False, verbose_name="Did you refuel the boat?")),
                ("has_new_damage", models.BooleanField(default=False, verbose_name="Did you discover new damage?")),
                ("new_damage_description", models.TextField(blank=True, verbose_name="New damage description")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="reservations/boat-logbooks/", verbose_name="Photo of the boat")),
                ("reservation", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="boat_logbook", to="reservations.reservation", verbose_name="Reservation")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
