# Generated by Django 5.2.14 on 2026-10-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_remove_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="request_status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Pending"), (1, "Approved"), (2, "Denied")],
                default=0,
                verbose_name="Request status",
            ),
        ),
    ]
