# Generated by Django 5.2.14 on 2026-10-05 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_add_groupmembership'),
        ('reservations', '0004_request_status_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservable',
            name='managed_by_group',
            field=models.ForeignKey(blank=True, help_text='The group whose members evaluate reservation requests for this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_reservables', to='groups.loefbijtergroup', verbose_name='Managed by group'),
        ),
        migrations.AddField(
            model_name='reservable',
            name='managed_by_user',
            field=models.ForeignKey(blank=True, help_text='The person who evaluates reservation requests for this item. Leave both managers empty to let the reservation administrators evaluate them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_reservables', to=settings.AUTH_USER_MODEL, verbose_name='Managed by person'),
        ),
        migrations.AddConstraint(
            model_name='reservable',
            constraint=models.CheckConstraint(condition=models.Q(('managed_by_group__isnull', True), ('managed_by_user__isnull', True), _connector='OR'), name='reservable_single_manager', violation_error_message='Choose either a group or a person as manager, not both.'),
        ),
    ]
