# Generated by Django 5.2.14 on 2026-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_request_status_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="logbook_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Logbook reminder sent at",
            ),
        ),
    ]
