# Generated by Django 5.2.14 on 2026-08-03 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_add_reservable_type_and_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservableBoat',
            fields=[
                ('reservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservable')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacity')),
                ('has_engine', models.BooleanField(default=False, verbose_name='Boat has an engine')),
                ('provider', models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Loefbijter'), (2, 'Ceulemans')], default=0, verbose_name='Boat provider')),
                ('requires_skippership', models.CharField(blank=True, choices=[('KB1', 'KB1'), ('KB2', 'KB2'), ('KB3', 'KB3'), ('Pico', 'Pico')], help_text='The skippership required to use this boat.', max_length=10, verbose_name='Required skippership')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('reservations.reservable',),
        ),
        migrations.CreateModel(
            name='ReservableMaterial',
            fields=[
                ('reservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservable')),
                ('size', models.CharField(max_length=10, verbose_name='Size')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('reservations.reservable',),
        ),
        migrations.CreateModel(
            name='ReservableRoom',
            fields=[
                ('reservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservable')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacity')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('reservations.reservable',),
        ),
        migrations.AlterField(
            model_name='boatdamagerecord',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_records', to='reservations.reservableboat', verbose_name='Boat'),
        ),
        migrations.RemoveField(
            model_name='boat',
            name='reservable_ptr',
        ),
        migrations.RemoveField(
            model_name='boatreservation',
            name='boat',
        ),
        migrations.RemoveField(
            model_name='boatreservation',
            name='reservation_ptr',
        ),
        migrations.RemoveField(
            model_name='boatreservation',
            name='skipper',
        ),
        migrations.RemoveField(
            model_name='complicationlog',
            name='reservable',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='reservable_ptr',
        ),
        migrations.RemoveField(
            model_name='gearreservation',
            name='gear',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RemoveField(
            model_name='room',
            name='reservable_ptr',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='room',
        ),
        migrations.AlterModelOptions(
            name='reservable',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='reservabletype',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterField(
            model_name='reservable',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reservable',
            name='is_reservable',
            field=models.BooleanField(default=True, help_text='When an item is unavailable for reservation, due to maintenance for example, set this to false.', verbose_name='Reservable'),
        ),
        migrations.AlterField(
            model_name='reservable',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Boardroom'), (2, 'Bastion'), (3, 'Kraaijenbergse Plassen')], default=0, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(end__gt=models.F('start')), name='end_gt_start', violation_error_message='End time cannot be before the start time.'),
        ),
        migrations.DeleteModel(
            name='Boat',
        ),
        migrations.DeleteModel(
            name='BoatReservation',
        ),
        migrations.DeleteModel(
            name='ComplicationLog',
        ),
        migrations.DeleteModel(
            name='Gear',
        ),
        migrations.DeleteModel(
            name='GearReservation',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomReservation',
        ),
    ]
