# Generated by Django 5.2.14 on 2026-10-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservable_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reason',
            field=models.TextField(blank=True, help_text='What the reservation is for.', verbose_name='Reason'),
        ),
    ]
