[tool.poetry]
name = "loefsys"
description = "The in-house developed website of N.S.Z.V. Loefbijter."
authors = ["Loefbijter Webcie <webcie@loefbijter.nl>"]
license = "MIT License"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
argon2-cffi = "^23.1.0"
Django = "^5.0.6"
#django-allauth = "^0.63.5" To implement later
django-anymail = "^11.0"
django-classy-settings = "^3.0.4"
django-crispy-forms = "^2.2"
django-storages = { version = "^1.4.4", extras = ["boto3"] }
django-phonenumbers = "^1.0.1"
django-phonenumber-field = "^8.0.0"
django-localflavor = "^4.0"
dj-database-url = "^2.1.0"

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^4.4.2"

[tool.poetry.group.production]
optional = true

[tool.poetry.group.production.dependencies]
gunicorn = "^22.0.0"
#Collectfast = "^2.2.0" To implement later
psycopg2 = "^2.9.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
