# Generated by Copilot on behalf of user
from django.db import migrations, models
import django_extensions.db.fields
import django.db.models.deletion
import datetime
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("members", "0006_user_pod_split"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.loefbijtergroup",
                        verbose_name="Group",
                    ),
                ),
                ("chair", models.BooleanField(default=False, verbose_name="Chair")),
                (
                    "role",
                    models.CharField(
                        max_length=255, blank=True, verbose_name="Role", help_text="The role of this member"
                    ),
                ),
                (
                    "member_since",
                    models.DateField(
                        default=datetime.date.today,
                        verbose_name="Member since",
                        help_text="The date this member joined in this role",
                    ),
                ),
                (
                    "member_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Member until", help_text="A member until this time."
                    ),
                ),
                ("note", models.CharField(max_length=256, blank=True)),
            ],
            options={
                "get_latest_by": "modified",
            },
        ),
    ]
