# Generated by Django 5.2.14 on 2026-07-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganizer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='organizing_group', to='groups.loefbijtergroup'),
        ),
    ]
