# Generated by Django 5.1.5 on 2025-06-23 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganizer',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='datetimeregistrationinformation',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventregistration'),
        ),
        migrations.AddField(
            model_name='booleanregistrationinformation',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventregistration'),
        ),
        migrations.AddField(
            model_name='integerregistrationinformation',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventregistration'),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='integerregistrationinformation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.registrationformfield'),
        ),
        migrations.AddField(
            model_name='datetimeregistrationinformation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.registrationformfield'),
        ),
        migrations.AddField(
            model_name='booleanregistrationinformation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.registrationformfield'),
        ),
        migrations.AddField(
            model_name='textregistrationinformation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.registrationformfield'),
        ),
        migrations.AddField(
            model_name='textregistrationinformation',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventregistration'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'contact', 'status')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='registrationformfield',
            order_with_respect_to='event',
        ),
    ]
