# Generated by Django 5.2.14 on 2026-10-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "permissions": (
                    ("manage_other_events", "Can manage events in category Other"),
                    ("manage_alumni_events", "Can manage events in category Alumni"),
                    (
                        "manage_association_events",
                        "Can manage events in category Association",
                    ),
                    (
                        "manage_competition_events",
                        "Can manage events in category Competition",
                    ),
                    ("manage_leisure_events", "Can manage events in category Leisure"),
                    ("manage_sailing_events", "Can manage events in category Sailing"),
                    (
                        "manage_training_events",
                        "Can manage events in category Training",
                    ),
                )
            },
        ),
    ]
