# Generated by Django 5.2.14 on 2026-10-03 14:01

import django.db.models.deletion
import loefsys.events.models.event
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_activity_managers_group"),
        ("groups", "0002_add_groupmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "permissions": (
                    ("manage_other_events", "Can manage events in category Other"),
                    ("manage_alumni_events", "Can manage events in category Alumni"),
                    (
                        "manage_association_events",
                        "Can manage events in category Association",
                    ),
                    (
                        "manage_competition_events",
                        "Can manage events in category Competition",
                    ),
                    ("manage_leisure_events", "Can manage events in category Leisure"),
                    ("manage_sailing_events", "Can manage events in category Sailing"),
                    (
                        "manage_training_events",
                        "Can manage events in category Training",
                    ),
                ),
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.AlterModelOptions(
            name="eventorganizer",
            options={
                "verbose_name": "event organizer",
                "verbose_name_plural": "event organizers",
            },
        ),
        migrations.AlterModelOptions(
            name="eventregistration",
            options={
                "verbose_name": "registration",
                "verbose_name_plural": "registrations",
            },
        ),
        migrations.AlterModelOptions(
            name="registrationformfield",
            options={
                "verbose_name": "registration form field",
                "verbose_name_plural": "registration form fields",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="is_open_event",
            field=models.BooleanField(
                default=False,
                help_text="Event is open for non-members",
                verbose_name="Open event",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=loefsys.events.models.event.OverwriteStorage(),
                upload_to=loefsys.events.models.event.Event.event_picture_upload_path,
                verbose_name="Picture",
            ),
        ),
        migrations.AlterField(
            model_name="eventorganizer",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizing_group",
                to="groups.loefbijtergroup",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="eventorganizer",
            name="user",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="members",
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Member",
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
                verbose_name="Event",
            ),
        ),
    ]
