# Generated by Django 5.2.14 on 2026-08-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_add_skippership_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lichting',
            field=models.CharField(blank=True, help_text="The member's lichting, for example '57e lichting'.", max_length=100, verbose_name='Lichting'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, help_text='Additional title for the user, editable by the board.', max_length=100, verbose_name='Title'),
        ),
    ]
