# Generated by Copilot on behalf of user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_user_pod_split"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="loefbijter_groups",
            field=models.ManyToManyField(
                to="groups.LoefbijterGroup",
                verbose_name="Loefbijter groups",
                blank=True,
                help_text=(
                    "The groups this user belongs to. A user will get all permissions "
                    "granted to each of their groups."
                ),
                related_name="user_set",
                related_query_name="user",
            ),
        ),
    ]
