# Generated by Django 5.2.14 on 2026-10-01 15:27

import loefsys.members.models.user
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_add_loefbijter_groups_m2m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=50, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name_preference",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Show full name"),
                    (1, "Show full name with nickname"),
                    (2, "Show the nickname and last name"),
                    (3, "Show only the initials and the last name"),
                    (4, "Show only the first name"),
                    (5, "Show only the nickname"),
                ],
                default=0,
                verbose_name="Display name preference",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="note",
            field=models.TextField(blank=True, verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=loefsys.members.models.user.OverwriteStorage(),
                upload_to=loefsys.members.models.user.User.user_picture_upload_path,
                verbose_name="Profile picture",
            ),
        ),
    ]
