# Generated by Django 5.2.14 on 2026-10-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_admin_permission"),
        ("members", "0008_backfill_required_skipperships"),
        ("members", "0008_verbose_names"),
    ]

    operations = []
