# Generated by Django 5.2.14 on 2026-10-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_merge_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskippership',
            name='given_by',
        ),
    ]
