name: Django Tests CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    environment: default

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Add pipx to PATH
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          poetry --version

      - name: Debug PATH
        run: poetry --version


      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Run the tests
        run: poetry run test
