name: Docker Image CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default

    steps:
    - uses: actions/checkout@v3
    - name: Make production envfile
      if: github.ref == 'refs/heads/main'
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_DB_NAME: ${{ secrets.DB_NAME_PROD }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        directory: infra
        file_name: .env
        fail_on_empty: true
    - name: Make development envfile
      if: github.ref == 'refs/heads/dev'
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_DB_NAME: ${{ secrets.DB_NAME_DEV }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        envkey_DJANGO_DEBUG: True
        envkey_S3_STATIC_STORAGE: True
        directory: infra
        file_name: .env
        fail_on_empty: true
    - name: Build the Docker production image
      if: github.ref == 'refs/heads/main'
      run: docker build . --file infra/loefsys/Dockerfile --tag loefsys:$(date +%Y%m%d)
    - name: Build the Docker development image
      if: github.ref == 'refs/heads/dev'
      run: docker build . --file infra/loefsys/Dockerfile.dev --tag loefsys:$(date +%Y%m%d)
    - name: Run the Docker container
      run: echo "CID=$(docker run -d -i -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --rm loefsys:$(date +%Y%m%d))" >> $GITHUB_ENV
    - name: Call Zappa update production
      if: github.ref == 'refs/heads/main'
      run: docker exec ${{ env.CID }} zappa update prod
    - name: Call Zappa update development
      if: github.ref == 'refs/heads/dev'
      run: docker exec ${{ env.CID }} zappa update dev
    - name: Call Zappa migrate production
      if: github.ref == 'refs/heads/main'
      run: docker exec ${{ env.CID }} zappa manage prod migrate
    - name: Call Zappa migrate development
      if: github.ref == 'refs/heads/dev'
      run: docker exec ${{ env.CID }} zappa manage dev migrate
    - name: Upload static files to S3 prod bucket
      if: github.ref == 'refs/heads/main'
      run: docker exec ${{ env.CID }} zappa manage prod "collectstatic --no-input"
    - name: Upload static files to S3 dev bucket
      if: github.ref == 'refs/heads/dev'
      run: docker exec ${{ env.CID }} zappa manage dev "collectstatic --no-input"
    - name: Call Zappa certify production
      if: github.ref == 'refs/heads/main'
      run: docker exec ${{ env.CID }} zappa certify prod --yes
    - name: Call Zappa certify development
      if: github.ref == 'refs/heads/dev'
      run: docker exec ${{ env.CID }} zappa certify dev --yes
