name: Docker Image CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default

    steps:
    - uses: actions/checkout@v3
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_DB_NAME: ${{ secrets.DB_NAME }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        file_name: .env
        fail_on_empty: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag loefsys:$(date +%Y%m%d)
    - name: Run the Docker container
      run: echo "CID=$(docker run -d -i -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --rm loefsys:$(date +%Y%m%d))" >> $GITHUB_ENV
    - name: Call Zappa update
      run: docker exec ${{ env.CID }} zappa update dev
