name: Docker Image CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag loefsys:$(date +%Y%m%d)
    - name: Run the Docker container
      run: echo "CID=$(docker run -d -i -e AWS_ACCESS_KEY_ID=${{ secret.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secret.AWS_SECRET_ACCESS_KEY }} --rm loefsys:$(date +%Y%m%d))" >> $GITHUB_ENV
    - name: Call Zappa update production
      run: docker exec ${{ env.CID }} zappa update dev
