name: Docker Image CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default

    steps:
    - uses: actions/checkout@v3
    - name: Make production envfile
      if: github.ref == 'refs/heads/master'
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_DB_NAME: ${{ secrets.DB_NAME_PROD }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        file_name: .env
        fail_on_empty: true
    - name: Make development envfile
      if: github.ref == 'refs/heads/dev'
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_DB_NAME: ${{ secrets.DB_NAME_DEV }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        file_name: .env
        fail_on_empty: true
    - name: Build the Docker production image
      if: github.ref == 'refs/heads/master'
      run: docker build . --file Dockerfile --tag loefsys:$(date +%Y%m%d)
    - name: Build the Docker development image
      if: github.ref == 'refs/heads/dev'
      run: docker build . --file Dockerfile_dev --tag loefsys:$(date +%Y%m%d)
    - name: Run the Docker container
      run: echo "CID=$(docker run -d -i -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --rm loefsys:$(date +%Y%m%d))" >> $GITHUB_ENV
    - name: Call Zappa update production
      if: github.ref == 'refs/heads/master'
      run: docker exec ${{ env.CID }} zappa update prod
    - name: Call Zappa update development
      if: github.ref == 'refs/heads/dev'
      run: docker exec ${{ env.CID }} zappa update dev
