name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag loefsys:$(date +%Y%m%d)
    - name: Run the Docker container
      run: docker run -i -v "$(pwd):/var/task" -v ~/.aws/:/root/.aws --rm loefsys:$(date +%Y%m%d)
    - name: Call Zappa update production
      run: zappa update prod
