name: Github Pages CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    env:
      DJANGO_SECRET_KEY: django-insecure-loefbijter
      DJANGO_DATABASE_URL: sqlite:///db.sqlite
    permissions:
      contents: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Build HTML
        run: poetry run makedocs

      # - name: Correct file permissions
      #   shell: sh
      #   if: runner.os == 'Linux'
      #   run: |
      #     chmod -c -R +rX "docs/_build/html" |
      #     while read line; do
      #       echo "::warning title=Invalid file permissions automatically fixed::$line"
      #     done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: html-docs
          path: docs/_build/html
          # if-no-files-found: error

  deploy:
    needs: build

    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: html-docs
