name: Github Pages CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    env:
      DJANGO_SECRET_KEY: django-insecure-loefbijter
      DJANGO_DATABASE_URL: sqlite:///db.sqlite
    permissions:
      contents: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Build HTML
        run: poetry run makedocs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: html-docs
          path: docs/_build/html

  deploy:
    needs: build

    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: html-docs
